In [189]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [190]:
df=pd.read_csv('Algerian_forest_fires_dataset_UPDATE.csv' ,header=1)

In [191]:
df.head()

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,01,06,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4,0.5,not fire
1,02,06,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire
2,03,06,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire
3,04,06,2012,25,89,13,2.5,28.6,1.3,6.9,0,1.7,0,not fire
4,05,06,2012,27,77,16,0,64.8,3,14.2,1.2,3.9,0.5,not fire

In [192]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246 entries, 0 to 245
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          246 non-null    object
 1   month        245 non-null    object
 2   year         245 non-null    object
 3   Temperature  245 non-null    object
 4    RH          245 non-null    object
 5    Ws          245 non-null    object
 6   Rain         245 non-null    object
 7   FFMC         245 non-null    object
 8   DMC          245 non-null    object
 9   DC           245 non-null    object
 10  ISI          245 non-null    object
 11  BUI          245 non-null    object
 12  FWI          245 non-null    object
 13  Classes      244 non-null    object
dtypes: object(14)
memory usage: 27.0+ KB

In [193]:
df.drop(['day', 'month', 'year'], axis=1, inplace=True)
df.head()

  Temperature  RH  Ws Rain   FFMC  DMC    DC  ISI  BUI  FWI    Classes
0          29  57  18     0  65.7  3.4   7.6  1.3  3.4  0.5  not fire
1          29  61  13   1.3  64.4  4.1   7.6    1  3.9  0.4  not fire
2          26  82  22  13.1  47.1  2.5   7.1  0.3  2.7  0.1  not fire
3          25  89  13   2.5  28.6  1.3   6.9    0  1.7    0  not fire
4          27  77  16     0  64.8    3  14.2  1.2  3.9  0.5  not fire

In [194]:
df.columns

Index(['Temperature', ' RH', ' Ws', 'Rain ', 'FFMC', 'DMC', 'DC', 'ISI', 'BUI',
       'FWI', 'Classes  '],
      dtype='object')

In [195]:
df.columns= df.columns.str.strip()

In [196]:
df.columns

Index(['Temperature', 'RH', 'Ws', 'Rain', 'FFMC', 'DMC', 'DC', 'ISI', 'BUI',
       'FWI', 'Classes'],
      dtype='object')

In [197]:
df.iloc[[122]]

    Temperature   RH   Ws Rain FFMC  DMC   DC  ISI  BUI  FWI Classes
122         NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN

In [198]:
df.shape

(246, 11)

In [199]:
df.drop(121,inplace=True)

In [200]:
df.iloc[[122]]

     Temperature   RH   Ws   Rain  FFMC  DMC  DC  ISI  BUI  FWI    Classes
123  Temperature   RH   Ws  Rain   FFMC  DMC  DC  ISI  BUI  FWI  Classes

In [201]:
df

    Temperature  RH  Ws  Rain  FFMC  DMC    DC  ISI   BUI  FWI       Classes
0            29  57  18     0  65.7  3.4   7.6  1.3   3.4  0.5   not fire
1            29  61  13   1.3  64.4  4.1   7.6    1   3.9  0.4   not fire
2            26  82  22  13.1  47.1  2.5   7.1  0.3   2.7  0.1   not fire
3            25  89  13   2.5  28.6  1.3   6.9    0   1.7    0   not fire
4            27  77  16     0  64.8    3  14.2  1.2   3.9  0.5   not fire
..          ...  ..  ..   ...   ...  ...   ...  ...   ...  ...           ...
241          30  65  14     0  85.4   16  44.5  4.5  16.9  6.5       fire
242          28  87  15   4.4  41.1  6.5     8  0.1   6.2    0   not fire
243          27  87  29   0.5  45.9  3.5   7.9  0.4   3.4  0.2   not fire
244          24  54  18   0.1  79.7  4.3  15.2  1.7   5.1  0.7   not fire
245          24  64  15   0.2  67.3  3.8  16.5  1.2   4.8  0.5  not fire

[245 rows x 11 columns]

In [209]:
df.isnull().sum()

Temperature    0
RH             0
Ws             0
Rain           0
FFMC           0
DMC            0
DC             0
ISI            0
BUI            0
FWI            0
Classes        0
dtype: int64

In [210]:
df

    Temperature  RH  Ws  Rain  FFMC  DMC    DC  ISI   BUI  FWI       Classes
0            29  57  18     0  65.7  3.4   7.6  1.3   3.4  0.5   not fire
1            29  61  13   1.3  64.4  4.1   7.6    1   3.9  0.4   not fire
2            26  82  22  13.1  47.1  2.5   7.1  0.3   2.7  0.1   not fire
3            25  89  13   2.5  28.6  1.3   6.9    0   1.7    0   not fire
4            27  77  16     0  64.8    3  14.2  1.2   3.9  0.5   not fire
..          ...  ..  ..   ...   ...  ...   ...  ...   ...  ...           ...
241          30  65  14     0  85.4   16  44.5  4.5  16.9  6.5       fire
242          28  87  15   4.4  41.1  6.5     8  0.1   6.2    0   not fire
243          27  87  29   0.5  45.9  3.5   7.9  0.4   3.4  0.2   not fire
244          24  54  18   0.1  79.7  4.3  15.2  1.7   5.1  0.7   not fire
245          24  64  15   0.2  67.3  3.8  16.5  1.2   4.8  0.5  not fire

[243 rows x 11 columns]

In [206]:
df.columns

Index(['Temperature', 'RH', 'Ws', 'Rain', 'FFMC', 'DMC', 'DC', 'ISI', 'BUI',
       'FWI', 'Classes'],
      dtype='object')

In [207]:
x= df.drop(['Classes'], axis=1)
x

    Temperature  RH  Ws  Rain  FFMC  DMC    DC  ISI   BUI  FWI
0            29  57  18     0  65.7  3.4   7.6  1.3   3.4  0.5
1            29  61  13   1.3  64.4  4.1   7.6    1   3.9  0.4
2            26  82  22  13.1  47.1  2.5   7.1  0.3   2.7  0.1
3            25  89  13   2.5  28.6  1.3   6.9    0   1.7    0
4            27  77  16     0  64.8    3  14.2  1.2   3.9  0.5
..          ...  ..  ..   ...   ...  ...   ...  ...   ...  ...
241          30  65  14     0  85.4   16  44.5  4.5  16.9  6.5
242          28  87  15   4.4  41.1  6.5     8  0.1   6.2    0
243          27  87  29   0.5  45.9  3.5   7.9  0.4   3.4  0.2
244          24  54  18   0.1  79.7  4.3  15.2  1.7   5.1  0.7
245          24  64  15   0.2  67.3  3.8  16.5  1.2   4.8  0.5

[243 rows x 10 columns]

In [208]:
x.columns

Index(['Temperature', 'RH', 'Ws', 'Rain', 'FFMC', 'DMC', 'DC', 'ISI', 'BUI',
       'FWI'],
      dtype='object')